name: Deploy to Docker Hub and Push to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}z

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@3
      with:
        images: shotmeow/phygital-nextjs

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      env:
        NEXT_PUBLIC_ADMIN_LOGIN: ${{ secrets.ADMIN_LOGIN  }}
        NEXT_PUBLIC_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD  }}
        NEXT_PUBLIC_API_URL: ${{ secrets.API_URL  }}

    - name: SSH and restart docker-compose with new image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          docker-compose pull
          docker-compose restart
